version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - "50051:50051"  

  client:
    build:
      context: ./client
    ports:
      - "8080:8080" 
    depends_on:
      - server  
